[config_path]
    # Path to the observation(s)
    observation_path = '~/YOUR/PATH/formosa_desk/inversion_targetname/inputs/'
    
    # Path to the model
    model_path = '~/YOUR/PATH/formosa_desk/atm_grids/model.nc'
    
    # Path to store your interpolated grid
    adapt_store_path = '~/YOUR/PATH/formosa_desk/inversion_targetname/adapted_grid/'
    
    # Path to store your results
    result_path = '~/YOUR/PATH/formosa_desk/inversion_targetname/outputs'